import { Inter } from "next/font/google";
import "./globals.css";
import { FaLinkedin, FaTwitter, FaInstagram, FaGithub } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ingenuite",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <head>
        <link rel="icon" href="/logoIcon.png" />
      </head>
      <body className="relative" >
        <div className="bg-[#0a0a55] w-10 z-50 h-36 fixed top-[12rem] p-[3px] -left-1 " >
          <div className="flex flex-col  gap-3 justify-between bg-transparent border-2 border-l-0 border-red-500 items-center w-full h-full py-1 text-md" >
            <a target="_blank" href="https://www.github.com/geniusahyan" className="text-[blue]" ><FaGithub /> </a>
            <a target="_blank" href="https://www.instagram.com/_a._h.ya.n" className="text-[red]" ><FaInstagram /> </a>
            <a target="_blank" href="https://www.linkedin.com/in/aslam-alam-305193286/" className="text-[pink]" ><FaLinkedin /> </a>
            <a target="_blank" href="https://twitter.com/Aslam_Alam_07" className="text-[cyan]" ><FaTwitter /> </a>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
